name: "CI"

on:
  pull_request:
  push:
    branches: [master]
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0" # weekly on Sunday
    - cron: "0 0 25 * *" # monthly on the 25th

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: â„
    runs-on: ubuntu-latest
    strategy:
      matrix:
        host:
          - ionia
        config-type:
          - type: "ionia"
            path: ".#nixosConfigurations.{host}.config.system.build.toplevel"

    steps:
      - uses: actions/checkout@v4

      - uses: wimpysworld/nothing-but-nix@main
        with:
          hatchet-protocol: "rampage"
          root-safe-haven: "55296"
          mnt-safe-haven: "2048"
          witness-carnage: false

      - uses: DeterminateSystems/determinate-nix-action@main
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          extra-conf: |
            lazy-trees = true

      - uses: DeterminateSystems/flake-checker-action@main

      - uses: cachix/cachix-action@master
        with:
          name: xaolan
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          skipPush: ${{ github.ref != 'refs/heads/master' || github.event_name != 'push' }}

      # Monthly flake.lock update
      - name: Update flake.lock (Monthly)
        if: ${{ github.event_name == 'schedule' && github.event.schedule == '0 0 25 * *' }}
        uses: DeterminateSystems/update-flake-lock@v25
        with:
          token: ${{ secrets.GH_TOKEN }}
          branch: monthly-lock
          git-author-name: "bigbabyboost"
          git-author-email: "ah0199004@gmail.com"
          git-committer-name: "bigbabyboost"
          git-committer-email: "ah0199004@gmail.com"
          commit-msg: "chore(lockfile): update flake.lock"
          pr-title: "chore(lockfile): update flake.lock"
          pr-labels: |
            dependencies
            automated
            monthly

      # Weekly flake.lock update
      - name: Update flake.lock (Weekly)
        if: ${{ github.event_name == 'schedule' && github.event.schedule == '0 0 * * 0' }}
        uses: DeterminateSystems/update-flake-lock@v25
        with:
          token: ${{ secrets.GH_TOKEN }}
          branch: weekly-lock
          git-author-name: "bigbabyboost"
          git-author-email: "ah0199004@gmail.com"
          git-committer-name: "bigbabyboost"
          git-committer-email: "ah0199004@gmail.com"
          commit-msg: "chore(lockfile): update flake.lock"
          pr-title: "chore(lockfile): update flake.lock"
          pr-labels: |
            dependencies
            automated
            weekly

      # Show flake outputs
      - run: nix flake show

      # Optional: Build something from your flake like a devShell or system config
      - name: Build NixOS configuration
        run: |
          FLAKEREF="${{ matrix.config-type.path }}"
          FLAKEREF="${FLAKEREF/\{host\}/${{ matrix.host }}}"
          nix build ${FLAKEREF} -L

      - name: Info
        run: nix path-info -Sh ./result
      # Optional: Build dev shell to ensure it works
      - name: Build devShell
        run: nix develop --command true

      - name: sbomnix
        run: |
          name="${{ matrix.host }}-${{ matrix.config-type.type }}"
          nix run github:tiiuae/sbomnix#sbomnix -- \
            --csv "${name}.sbom.csv" \
            --cdx "${name}.sbom.cdx.json" \
            --spdx "${name}.sbom.spdx.json" \
            ./result
      - name: vulnxscan
        run: |
          name="${{ matrix.host }}-${{ matrix.config-type.type }}"
          nix run github:tiiuae/sbomnix#vulnxscan -- \
            --triage \
            --sbom "${name}.sbom.cdx.json"
          if [ -e vulns.triage.csv ]; then
            grep -v -E "not_vulnerable|fix_not_available" vulns.triage.csv > cve.csv
            if [ $(wc -l < cve.csv) -gt 1 ]; then
              nix run github:nixos/nixpkgs#csv2md -- --columns "0-7,9" cve.csv | tee "${name}.vulnxscan.md"
              echo "### Vulnerability Scan Results for ${{ matrix.host }}-${{ matrix.config-type.type }}" >> $GITHUB_STEP_SUMMARY
              echo "" >> $GITHUB_STEP_SUMMARY
              cat "${name}.vulnxscan.md" >> $GITHUB_STEP_SUMMARY
              echo "" >> $GITHUB_STEP_SUMMARY
            fi
          fi
